name: Analyze Code Changes

on:
  push:
    branches:
      - master  # Change this to your default branch
      - master_UAT  # Change this to your default branch

jobs:
  analyze-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print a message
        run: echo "GitHub Actions is working!"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt  # Ensure you have a requirements.txt file if dependencies are needed

      - name: Identify changed files
        id: changes
        run: |
          git diff ${{ github.event.before }} ${{ github.sha }} > changed_files.txt

      - name: Run analysis script
        run: |
          python trigger_dependency_analysis.py changed_files.txt

      - name: Upload generated files
        uses: actions/upload-artifact@v2
        with:
          name: generated-files
          path: |
            changes_for_further_analysis.json
            # Add other files or directories you want to upload here          

  check_and_download:
    runs-on: ubuntu-latest
    needs: analyze-changes
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check if the analyze-changes job was successful
        if: ${{ needs.analyze-changes.result == 'success' }}
        run: |
          # Get the current workflow run ID
          RUN_ID=${{ github.run_id }}

          REPO_OWNER="AmyGB-ai"
          REPO_NAME="IKG"
          ARTIFACT_NAME="generated-files"
          GITHUB_TOKEN="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"

          echo "LATEST RUN ID->$RUN_ID"
          sleep 10
          echo "curl -H Authorization: token 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 https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts"
          _URL=$( curl -H "Authorization: token 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" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" )
          
          echo "LATEST URL-> $_URL"   
          #ARTIFACT_URL=$(curl -H "Authorization: token $GITHUB_TOKEN" \
          #  "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" \
          #  | jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .archive_download_url")                                                                                    
          #curl -L -H "Authorization: token $GITHUB_TOKEN" -o $ARTIFACT_NAME.zip $ARTIFACT_URL

          #echo "Artifact downloaded and extracted successfully."           
